### PR TITLE
Portfolio: Details popup window

### PR DESCRIPTION
**Pull request by Ali-0111**
### **### Learning objectives*
1. Use basic JavaScript syntax.
2. Use JavaScript to manipulate DOM elements.
3. Use JavaScript events.
4. Understand how to parse a Figma design to create a UI.
5. Use objects to store and access data.

**### **### Project Requirements****

1. You should implement the following interactions:
2. When the user clicks (or taps) the button to check project details, the popup with details about the project appears.
3. When the user clicks (or taps) the close (X) button, the popup disappears.
4. In order to associate each project with the popup window details, you must refactor the project section:
5. You need to use a JavaScript array to store all of the information for all projects.
6. For each project you need to store the following pieces of data in a JavaScript object, at a minimum: name, description, featured image, technologies, link to live version, link to source.
7. You need to update the main page so that the projects section is created dynamically using the information stored in that JavaScript object. Remember, all of the HTML in that section is created when the page loads.
8. After that, you could implement the popup window.
**Note : Kindly ignore, pair comments, I did not have any partner. he left on Monday.**

### CODE REVIEW

**Review by NahnahAJ — COMMENTED** [review]
Hi @Ali-0111 , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.


## Invalid Code Review Request
- [ ] You have submitted a project that is missing a professional pull request description. Kindly fix this :+1: 
- Your Pull Request Now
image
- [ ] I also noticed that you didn't install Eslint linters for the to check errors for the javascript file you added for the popup so kindly refer to the [Html, Css and Js linters](https://github.com/microverseinc/linters-config/tree/master/html-css-js) setup file and set up your linters to include `eslint`.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @NahnahAJ in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by osamaashraf6 — COMMENTED** [review]
Hi @Ali-0111 😊, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request 🆘💀

You have submitted a project, that : 

1. You 😃didn't install Eslint linters to check errors for the javascript file you added for the popup so kindly refer to the [Html, CSS, and Js linters](https://github.com/microverseinc/linters-config/tree/master/html-css-js) setup file and set up your linters to include eslint.
2. This milestone is a pair programming and I see at the commit that there is only one you have committed,so please let your partner pair with you at this activity as it is a pair programming activity😊

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by Ali-0111** [comment]
@osamaashraf6  
**### Hi, I did not have any partner in this week. so , please ignore this.**
2: I have installed eslint and stylint packages. I attached the result then I use npx command
A: npx eslint .
image
B: npx stylelint "**/*.{css,scss}"
image

**Review by Whoistolu — APPROVED** [review]
### Hi @Ali-0111 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 

# STATUS: APPROVED 🟢
**Congratulations! 🎉** 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @whoistolu in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by Whoistolu — APPROVED** [review]
### Hi @Ali-0111 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 

# STATUS: APPROVED 🟢
**Congratulations! 🎉** 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @whoistolu in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
